var person = { name: "ramanan", age: 39 };
//console.log(person);
// console.log(name);
//consloe.log(age);
//console.log(person.name);
//console.log(person.age);
//console.log(person["name"]);
//console.log(person["age"]);
//var evaluations = [7, 10, 9];
//console.log(evaluations);
var color = ["groen", "blauw", "rood"];
//console.log(color);
//console.log(color.length);
//console.log(color[0]);
//console.log(color[2]);
//var total = color.push("geel", "5");
//console.log(color);
var total = color.push({ greeting: "Hi ik ben een object" });
//console.log(color);
console.log(color[3]);